"""initial schema

Revision ID: ca8044ba4888
Revises: 
Create Date: 2026-04-02 18:28:44.784426
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca8044ba4888'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True, comment='salesforce, google_sheets, hubspot, etc.'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True, comment='Customer, Prospect, Partner'),
    sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True, comment='JSON or structured address'),
    sa.Column('p2b_score', sa.Integer(), nullable=True, comment='Propensity to Buy (0-100)'),
    sa.Column('account_signal', sa.Text(), nullable=True, comment='AI-generated strategic signal'),
    sa.Column('suggested_contacts_json', sa.Text(), nullable=True, comment='Cached buying committee JSON'),
    sa.Column('enrichment_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_accounts_external', 'accounts', ['source_system', 'external_id'], unique=True)
    op.create_table('ai_usage_logs',
    sa.Column('endpoint', sa.String(length=100), nullable=False, comment='Briefing Agent, Chat Agent, Raw Model'),
    sa.Column('operation', sa.String(length=100), nullable=False, comment='Briefing, Chat, Enrichment, SmartRouter'),
    sa.Column('user_identifier', sa.String(length=255), nullable=True, comment='Email or API key identity'),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='account, contact, opportunity'),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Total token consumption'),
    sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Prompt token count'),
    sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Completion token count'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Round-trip time in milliseconds'),
    sa.Column('cache_hit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='success', nullable=False, comment='success or error'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='e.g. gemini-2.5-pro, gemini-2.0-flash'),
    sa.Column('agent_id', sa.String(length=255), nullable=True, comment='Reasoning Engine ID'),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context (source_system, request params, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_usage_logs_created', 'ai_usage_logs', ['created_at'], unique=False)
    op.create_index('idx_ai_usage_logs_entity', 'ai_usage_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_ai_usage_logs_user', 'ai_usage_logs', ['user_identifier', 'created_at'], unique=False)
    op.create_table('briefing_cache',
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='account, contact, or opportunity'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='FK to accounts, contacts, or opportunities'),
    sa.Column('briefing_markdown', sa.Text(), nullable=True, comment='Full AI briefing in Markdown'),
    sa.Column('contact_briefing_markdown', sa.Text(), nullable=True, comment='Contact-specific executive briefing'),
    sa.Column('p2b_score', sa.Integer(), nullable=True, comment='Propensity to Buy at generation time (0-100)'),
    sa.Column('account_signal', sa.Text(), nullable=True, comment='Strategic signal snapshot'),
    sa.Column('why_we_matter', sa.Text(), nullable=True, comment='Value proposition statement'),
    sa.Column('anticipated_objection', sa.Text(), nullable=True, comment='Most likely executive objection'),
    sa.Column('objection_pivot', sa.Text(), nullable=True, comment='Strategic pivot to redirect'),
    sa.Column('suggested_contacts_json', sa.Text(), nullable=True, comment='Buying committee suggestions JSON'),
    sa.Column('cache_ttl_days', sa.Integer(), server_default='7', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='generated_at + cache_ttl_days interval'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_briefing_cache_entity', 'briefing_cache', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_briefing_cache_lookup', 'briefing_cache', ['entity_type', 'entity_id', 'expires_at'], unique=False)
    op.create_table('platform_config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment='gcp, ai, cache, auth, feature'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('contacts',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contacts_account', 'contacts', ['account_id'], unique=False)
    op.create_index('idx_contacts_external', 'contacts', ['source_system', 'external_id'], unique=True)
    op.create_table('opportunities',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True, comment='AI-generated next action from stalled pipeline analysis'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opportunities_account', 'opportunities', ['account_id'], unique=False)
    op.create_index('idx_opportunities_external', 'opportunities', ['source_system', 'external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_opportunities_external', table_name='opportunities')
    op.drop_index('idx_opportunities_account', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('idx_contacts_external', table_name='contacts')
    op.drop_index('idx_contacts_account', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('platform_config')
    op.drop_index('idx_briefing_cache_lookup', table_name='briefing_cache')
    op.drop_index('idx_briefing_cache_entity', table_name='briefing_cache')
    op.drop_table('briefing_cache')
    op.drop_index('idx_ai_usage_logs_user', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_logs_entity', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_logs_created', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index('idx_accounts_external', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
